# Generated by Django 5.1.6 on 2025-02-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='is_movie',
            field=models.BooleanField(default=True),
        ),
    ]
