# Generated by Django 5.1.6 on 2025-02-22 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_content_is_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username<built-in function id>', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='The username must start with a letter and contain only letters, numbers, underscores, or hyphens.', regex='^[a-zA-Z][a-zA-Z0-9_-]*$')]),
            preserve_default=False,
        ),
    ]
