# Generated by Django 5.1.6 on 2025-02-22 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='signup',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='The username must start with a letter and contain only letters, numbers or underscores.', regex='^[a-zA-Z][a-zA-Z0-9_]*$')]),
        ),
    ]
